version: '3'
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=maciej
      - MYSQL_DATABASE=product
      - MYSQL_USER=maciej
      - MYSQL_PASSWORD=123
    volumes:
      - /data/mysql
  config-server:
    image: config-server:1
    build:
      context: ./config-service
      dockerfile: Dockerfile
  product_service:
    image: product_service:1
    build:
      context: ./product_service
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    depends_on:
      - mysqldb
      - config-server
    volumes:
      - /data/product_service

